builds:
  -
    id: "aiagent"
    binary: aiagent
    main: ./cmd/aiagent/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  -
    id: aiagent-binaries
    name_template: "aiaigent-{{ .Os }}_{{ .Arch }}_{{ .Version }}"
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
nfpms:
  -
    file_name_template: "aiagent_package_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: Michael Paepcke
    homepage: https://paepcke.de/aiagent
    maintainer: Michael Paepcke <git@paepcke.de>
    description: aiagent
    license: BSD 3-Clause
    formats:
      - deb
      - rpm
